### PR TITLE
Fixing Chemex notebook

### PR DESCRIPTION
**Pull request by dfm**
I got the Chemex notebook working. I really only made 2 changes, but I'm not sure which is the key or if they were both needed, but now it's getting the right answer and it's fast. The changes were:

1. The prior on `y` was wrong. It needed to be `sd=np.sqrt(truths["power"])`
2. I converted to ppt instead of relative flux (you know me!) because there were some insane numerical issues (the entries in `W` were >1e8).

I'm not actually 100% sure that the likelihood is correct - we should write it down somewhere clearly.

### CODE REVIEW

**Comment by dfm** [comment]
Based on Luger et al, I'm pretty sure that this is what we want is this:

```python
map = starry.Map(ydeg=truths["ydeg"])
with pm.Model() as model:

    # Priors on the things we're solving for
    period = pm.Uniform("period", 8.4, 8.6)
    inc = pm.Uniform("inc", 50, 90)
     
    # Compute the model using starry
    theta = 360.0 * t / period
    XFull = map.linear_op(theta=theta, inc=inc)
    X0 = XFull[:, 0]
    X = XFull[:, 1:]
    
    # Solve the least squares problem
    XT = X.T / truths["flux_err"] ** 2
    XTX = tt.dot(XT, X)
    LInv = tt.diag(1.0 / truths["power"])
    W = XTX + LInv
    XTf = tt.dot(XT, flux)
    
    # Cholesky decomposition
    cho_W = tt.slinalg.cholesky(W)
    Q = tt.slinalg.solve_lower_triangular(cho_W, XTf)
    y = tt.slinalg.solve_upper_triangular(cho_W.T, Q)
    
    # Get the MAP flux model
    flux_model = tt.dot(X, y)
    
    # Compute the marginal likelihood following Luger et al (2017)
    loglike = 0.5*tt.dot(XTf.T, y)-tt.sum(tt.log(tt.diag(cho_W)))
    pm.Potential("loglike", loglike)
        
    # Track some values for plotting later
    pm.Deterministic("y", y)

    # Save our initial guess
    model_guess = xo.eval_in_model(flux_model)
```

But when I run this, I get *exactly* the same answer as the one in the existing notebook. So. It must be right… :) It seems like this should be faster because it requires fewer computations, but I get about the same performance so it probably doesn't matter.

**Comment by rodluger** [comment]
@dfm Awesome, thanks! Did you run this on your laptop? Even after your changes, I'm getting the same slow run times:

image

(You were clocking in at 4 draws/s, an order of magnitude faster. For some reason yours only ran with two parallel chains.)

What gives? I'm up to date on exoplanet (0.1.6) and pymc3 (3.6) and obviously starry (1.0.0.dev1).

**Comment by dfm** [comment]
Mine only runs 2 chains because PyMC3 thinks I only have 2 cores (I actually have 4 - and it ends up using all 4 because the linear algebra is parallelized). But that shouldn't have a huge effect.

To compare the performance across machines, will you run the following after initializing the model:

```python
with model:
    func = xo.get_theano_function_for_var(model.logpt)
    grad = xo.get_theano_function_for_var(theano.grad(model.logpt, model.vars))
    vars = xo.get_args_for_theano_function()

func(*vars)
grad(*vars)
%timeit func(*vars)
%timeit grad(*vars)

pfunc = xo.get_theano_function_for_var(model.logpt, profile=True)
pfunc(*vars)

pgrad = xo.get_theano_function_for_var(theano.grad(model.logpt, model.vars), profile=True)
pgrad(*vars)

pfunc.profile.summary()
pgrad.profile.summary()
```

[This](https://gist.github.com/dfm/774092b622eaf639358db9f9fa2519e1) is what I get…

**Comment by rodluger** [comment]
Hmm the timing is [similar](https://gist.github.com/dfm/774092b622eaf639358db9f9fa2519e1#gistcomment-2899967)...

**Comment by dfm** [comment]
Very strange! I'm out for the rest of the weekend, but we can look into it more on Monday.

**Comment by rodluger** [comment]
Cool, no rush. Interestingly, if I force `cores=1`, I get it to run in about 10 minutes, which is about how long yours took, and I get a very similar number of effective samples. So something is up with the multithreading! We can chat more next week.

**Comment by rodluger** [comment]
@dfm You know what, I think it's a memory issue. Within C++, I pre-allocate a bunch of matrices used throughout the computation of the design matrix. If there are multiple processes computing the flux using the same `Map` instance, there's a good chance that they'll overwrite each other's data at some point in the calculation, causing the sampler to go haywire. If this is the case, we'll either need to find a way to instantiate one `Map` per thread or I'll need to figure out how to make `starry` thread-safe.

**Pull request merged**
