### PR TITLE
[ReadyForReview] Add a convenience function for nexsci downloads

### PR DESCRIPTION
**Pull request by christinahedges**
Hi Rodrigo,

I changed the PR so that it now works on the dev branch. I'm opening it as a Work In Progress so you can tell me if you like this as a structure/API design. Let me know if you think it's not quite right and I will change it!

At the moment I'm getting an error from the dev branch where I can't initialize a `Map`, but I imagine that is a very temporary bug!

Thanks,
Christina

### CODE REVIEW

**Comment by rodluger** [comment]
This looks great. What's the exact error you're getting with the `Map` instance?

**Comment by christinahedges** [comment]
This is what happens for me at the moment:

image

**Comment by rodluger** [comment]
I suspect you just need to re-compile the C code. Make sure you have the most up to date commit on the dev branch, remove the `build` directory, and re-run `setup.py`. Let me know if that works. Also, the Azure build failed but only because of an authentication issue; I need to fix my pipeline to get PRs from other users to work. The tests are all passing.

**Comment by christinahedges** [comment]
Awesome thanks that worked great. 

One thing that I'm having a little trouble with and I want to get right is matching the nexsci orbital parameters to the starry orbital parameters. 

These are the column definitions they have:
https://exoplanetarchive.ipac.caltech.edu/docs/API_exoplanet_columns.html

Could you tell me which columns/combination of columns I should be using for the `Omega` and `w` parameters? I want to make sure I get it right!

**Comment by rodluger** [comment]
Good question. I think the value on the archive `pl_orblper` is the longitude of periastron, which is [equal to the sum](https://en.wikipedia.org/wiki/Longitude_of_the_periapsis) of the `Omega` and `w` angles in `starry`. The longitude of ascending node `Omega` is not an observable for transits/secondary eclipses, so you could just set that to zero, in which case `pl_orblper = w`.

**Comment by christinahedges** [comment]
That's great! I've added that in. Here are the big changes that this PR currently has:

- Added an `extensions` module
- Added `nexsci.py`, which includes hidden functions for querying nexsci
- In order to prevent the user having to query nexsci every time they want a light curve (which can add up in time and requires an internet connection) a csv file of all the planet data is stored in the package. This file is currently ~1Mb (>0.5% of the current package size), but it's worth watching out that in the future this file doesn't balloon. (It is possible to trim down this file a little by getting rid of extra columns, but some of them may end up being useful in the future.)
- Added a `data` folder in `extensions`, which will hold the csv file for planet data (`planets.csv`)
- When the user imports `extensions` it checks to find `planets.csv`. If the `planets.csv` file is 7 days out of date, the extension will try to redownload the file. 
- Added the `from_nexsci` function, which returns a `starry` system based on an input name, which you can call using

```python
from starry import extensions
import numpy as np
sys = extensions.from_nexsci('K2-18')
model = sys.flux(np.arange(0, 10, 0.01)).eval()
```

I haven't added any tests yet, but I'm about to. Before I do, testing this thoroughly requires that the CI can query nexsci to get the planet data file. This could break if, for example, nexsci has a problem and temporarily goes down. It doesn't seem ideal that this would break starry tests. I think the best solution is to test everything other than the online retrieval function. Does that sound good to you?

**Comment by rodluger** [comment]
Awesome! Pull from my dev branch and you'll see I added [a directory for extension tests](https://github.com/rodluger/starry/tree/dev/starry/extensions/tests). If possible, write tests to ensure your code works with both the lazy and greedy modes. Also, do write a test to query nexsci, but decorate it with `@pytest.mark.xfail` so that its failure doesn't break the build. I think it might make sense to trigger a separate build for the extensions, at which point we can have separate badges for the main code and each of the extensions, so the failure of one won't affect the other.  Does that sound good?

**Comment by christinahedges** [comment]
That sounds awesome, I'm away at the T'DA hack week but I'll get this done as soon as I have a spare hour! 👍

**Comment by christinahedges** [comment]
Hi Rodrigo, I added some tests for the nexsci extension, I think it looks good to me now, would you mind having a review of it and I'll make any updates you need? Thanks! C

**Comment by rodluger** [comment]
Sweet! I merged this so I can play around with it & tweak my Azure Pipelines build. I'll let you know if I need you to look over stuff again.

**Comment by rodluger** [comment]
Hey, I reorganized some stuff and merged it. I created a docs page for the extensions. Can you add some slightly more detailed docs, maybe with an example, and issue a new PR for it? I mostly want to try out my new Azure pipelines workflow and my badge generation (check out the README!) Note that I am now testing the main code and the extensions separately, so I removed the `xfail` marker from the nexsci test. Thanks for helping out with this! Keep the contributions coming...

**Pull request merged**
