### PR TITLE
Bugfix for `from_nexsci` extension

### PR DESCRIPTION
**Pull request by christinahedges**
The `from_nexsci` extension redownloads the `planets.csv` driver file if it notices that it is more than 7 days out of date. If it finds the file to be out of date, it warns the user that it is redownloading the file. Unfortunately, I forgot to actually import the logging module so that it can log that message to the user. This was causing the extension not to be importable, because it couldn't find the `log` variable.

This little bugfix imports the `logging` module, and sets up a `logger` variable in the same way that the rest of starry does.

Sorry for the bug, it was a hard one to test without an out of date file!

### CODE REVIEW

**Comment by rodluger** [comment]
Cool, thanks for catching this. There were some other places where you were calling `warn`, so I fixed all this locally. I also stopped tracking `planets.csv` -- I think it's best to just download it from source when the package is imported for the first time, rather than keep an old version in the repo.

**Comment by christinahedges** [comment]
Ah perfect! Sorry I missed a few. And that works for me with the `planets.csv`! I think originally I included it because it's nice to have incase you try to use it without an internet connection, but it's probably ok to assume most people do most of the time!

**Comment by rodluger** [comment]
There are a few other small issues, working on them now. Will push soon.

**Comment by rodluger** [comment]
I understand about not having an internet connection, but this only applies to the first time you use the extension. Plus, in order to install starry you need an internet connection in the first place. I suppose you could have a user who installs starry and some time later tries to use nexsci for the first time without an internet connection, but I think that's a pretty rare case.

**Pull request closed without merging**
