### PR TITLE
Insanity

### PR DESCRIPTION
**Pull request by rodluger**
- Removed all python code. Everything is C++, with a few functions that call the Python routines in starry_maps (for plotting and importing maps).

- Added support for multiprecision. Users can now request higher precision in the solver via Boost's multiprecision types. This fixed the numerical issues I was having for large Ylm degree, but is hella slow.

### CODE REVIEW

**Comment by ericagol** [comment]
On 3/27/18 3:58 PM, Rodrigo Luger wrote:
>
>  *
>
>     Removed all python code. Everything is C++, with a few functions
>     that call the Python routines in starry_maps (for plotting and
>     importing maps).
>
>  *
>
>     Added support for multiprecision. Users can now request higher
>     precision in the solver via Boost's multiprecision types. This
>     fixed the numerical issues I was having for large Ylm degree, but
>     is hella slow.
>
I'm guessing there is a better way.  For the large r/b problem, you 
could use an approximation
such as the edge of the star being straight or quadratic as it occults 
the planet, or something
similar to the "small planet approximation" in Mandel & Agol.  I did 
something like this
for lensing + occulation in 
http://adsabs.harvard.edu/abs/2003ApJ...594..449A

**Comment by rodluger** [comment]
@ericagol Thanks for the link! I tried something similar already but didn't get anywhere. Here's what I tried: Assuming the occultor is along the +y axis, its limb can be approximated as `y = (b-r) + x ** 2 / (2 * r). If I try to solve the double integral directly, I end up with some nasty mix of arctangents and square roots when I get to the outer (x) integral. If I use Green's theorem to integrate my `G_n` functions along the parabola, I still get functions of the form `(1 - x^2 - y^2)^0.5` in my integrand, where `y` is the parabola above. They don't look immediately analytic or tractable. I'll poke around your paper, but do you remember what you did?

**Comment by rodluger** [comment]
@ericagol Here's my error analysis, plotting the RMS as a function of occultor radius for each spherical harmonic degree:
image
The arrows show the radius at which the solution becomes unstable at the ppm level for a given degree. For Earth around the Sun, we can only use up to `l = 2`.
Finding an approximate solution would be great!

**Comment by rodluger** [comment]
@ericagol In the limit that the occultor limb is a straight line, I can use Green's theorem to get expressions of the form

image

which evaluate to square roots and arc tangents for all values of `n`. I'm sure I can find a recurrence relation in the G&R book for these.

However, the numerical instabilities tend to take over *before* this approximation becomes valid, so a quadratic approximation would be ideal.

**Pull request merged**
