### PR TITLE
Here's an example C op for the new starry

### PR DESCRIPTION
**Pull request by dfm**
Most of the changes are just moving the libraries around. We need to package Eigen inside the starry directory because Theano needs to be able to find it when it compiles the op.

The key files to look at are:

- `starry/include/theano_interface.h`: This defines some helper functions for converting between numpy types input by Theano and what we need for starry.
- `starry/ops/sT.py`: The wrapper code for the op. Similar to what you already had.
- `starry/ops/sT.cc`: The C implementation of the op. I'm not sure that I did everything right here, but this is the meat of it. Take a look!

### CODE REVIEW

**Comment by dfm** [comment]
Here are the relevant links:

- [theano_interface.h](https://github.com/rodluger/starry/blob/ae0116f6a3645ea2e3f4c95de721b9ffe5783f2a/starry/include/theano_interface.h)
- [sT.py](https://github.com/rodluger/starry/blob/ae0116f6a3645ea2e3f4c95de721b9ffe5783f2a/starry/ops/sT.py)
- [sT.cc](https://github.com/rodluger/starry/blob/ae0116f6a3645ea2e3f4c95de721b9ffe5783f2a/starry/ops/sT.cc)

**Comment by dfm** [comment]
PS there's also [a test](https://github.com/rodluger/starry/blob/ae0116f6a3645ea2e3f4c95de721b9ffe5783f2a/starry/ops/sT_test.py)

**Comment by rodluger** [comment]
@dfm Thank you! This works great. One question: several of my ops make use of the same [starry::Ops](https://github.com/rodluger/starry/blob/ae0116f6a3645ea2e3f4c95de721b9ffe5783f2a/starry/ops/sT.cc#L43) object. You wrote some logic to prevent re-allocation of this object within the ``sT`` op, but will this also work for other ops as well?

**Comment by dfm** [comment]
Ah - interesting. I do not know how to do that and I bet it's hard. Ops are really designed to be standalone. Let me think about that a bit and get back to you.

**Comment by rodluger** [comment]
Cool. This is really only important for the rotation ops, which all depend
on the same Wigner matrices. But I could probably just deal with it if they
each have to initialize their own memory.

**Comment by rodluger** [comment]
Working on this on the `dev` branch.

**Pull request closed without merging**
