### PR TITLE
Adding azure pipeline to build wheels

### PR DESCRIPTION
**Pull request by dfm**
This will build wheels for Linux and Mac and Python 3.6 and 3.7 that you can upload to PyPI.

I couldn't get Windows to work in the end because there were a bunch of compiler errors.

Most of the heavy lifting is done by [cibuildwheel](https://github.com/joerick/cibuildwheel) and, after you enable this pipeline, the built wheels will be uploaded for each commit to azure something like the following: https://dev.azure.com/foremanmackey/starry/_build/results?buildId=393&view=artifacts

### CODE REVIEW

**Comment by dfm** [comment]
Are you interested in merging this? If so, I can fix the merge conflicts. If not, I'll open a separate pull request with just the changes that fix the installation issues.

**Comment by rodluger** [comment]
@dfm Yes, please do fix the merge conflicts and I'll accept it. Can you move the YAML file to the .ci folder?

**Comment by dfm** [comment]
OK - should be all set. The main change from your perspective is the switch to having a `starry_version.py` file for the version number. This makes the build progress a bit simpler.

**Comment by rodluger** [comment]
Sweet, thank you!

**Pull request merged**
